# Generated by Django 4.1.7 on 2023-08-29 21:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("open_source", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opensourceproject",
            name="screenshot_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
