# Generated by Django 4.1.7 on 2023-08-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("experience", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="city",
            field=models.CharField(default="Moscow", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="experience",
            name="country",
            field=models.CharField(default="Russia", max_length=100),
            preserve_default=False,
        ),
    ]
