# Generated by Django 4.1.7 on 2023-08-29 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("experience", "0002_experience_city_experience_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
