# Generated by Django 4.1.7 on 2023-09-01 20:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("experience", "0003_experience_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="experience",
            options={"ordering": ["id"]},
        ),
    ]
