# Generated by Django 4.1.7 on 2023-12-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("experience", "0004_alter_experience_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
