# Generated by Django 4.2.4 on 2024-02-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0005_experience_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='description_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='job_title_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='job_title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='job_title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
