# Generated by Django 4.1.13 on 2024-02-26 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0006_experience_description_de_experience_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='description_de',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='job_title_de',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='job_title_en',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='job_title_ru',
        ),
    ]
