# Generated by Django 4.1.13 on 2024-02-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0007_remove_experience_description_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='company_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='company_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='job_title_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='job_title_en',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
