# Generated by Django 4.1.7 on 2023-09-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("job_title", models.CharField(max_length=255)),
                ("url", models.URLField()),
                ("location", models.CharField(max_length=255)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("responded", models.BooleanField(default=False)),
                ("cover_letter", models.TextField(blank=True, null=True)),
                ("response_received", models.BooleanField(default=False)),
                ("phone_interview_invited", models.BooleanField(default=False)),
                ("phone_interview_date", models.DateTimeField(blank=True, null=True)),
                ("phone_interview_done", models.BooleanField(default=False)),
                ("onsite_interview_invited", models.BooleanField(default=False)),
                ("onsite_interview_date", models.DateTimeField(blank=True, null=True)),
                ("onsite_interview_done", models.BooleanField(default=False)),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                (
                    "salary_range",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "final_decision",
                    models.CharField(
                        blank=True,
                        choices=[("accepted", "Accepted"), ("rejected", "Rejected")],
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
