# Generated by Django 4.1.13 on 2024-03-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0004_jobapplication_other_benefits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='other_benefits',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
