# Generated by Django 4.1.13 on 2024-03-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0005_alter_jobapplication_other_benefits'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='minuses',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
