# Generated by Django 4.1.13 on 2024-03-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0006_jobapplication_minuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='required_experience',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
