# Generated by Django 4.1.13 on 2024-03-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0007_jobapplication_required_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='cv_intro',
            field=models.TextField(blank=True, null=True),
        ),
    ]
