# Generated by Django 4.1.13 on 2024-03-03 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0009_alter_jobapplication_is_remote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='german_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='required_experience',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
