# Generated by Django 4.1.13 on 2024-03-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0010_alter_jobapplication_german_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='vacation_days',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
