# Generated by Django 4.1.13 on 2024-03-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0013_alter_jobapplication_cover_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
