# Generated by Django 4.1.13 on 2026-06-25 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0008_experience_company_de_experience_company_en_and_more'),
        ('job_application', '0016_alter_jobapplication_other_benefits'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplicationExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experience.experience')),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_experiences', to='job_application.jobapplication')),
            ],
            options={
                'unique_together': {('job_application', 'experience')},
            },
        ),
    ]
