# Generated by Django 4.1.13 on 2026-07-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0017_add_job_application_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='full_text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Full text (RU)'),
        ),
    ]
