# Generated by Django 4.1.13 on 2026-07-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0018_jobapplication_full_text_ru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='cv_intro',
            field=models.TextField(blank=True, null=True),
        ),
    ]
