# Generated by Django 4.1.13 on 2026-07-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0019_alter_jobapplication_cv_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='company_research',
            field=models.TextField(blank=True, null=True, verbose_name='Company research (RU)'),
        ),
    ]
