# Generated by Django 4.1.13 on 2026-07-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0020_jobapplication_company_research'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='ats_assessment',
            field=models.TextField(blank=True, null=True, verbose_name='ATS assessment (RU)'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='ats_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='ATS score (0-10)'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='ats_verdict',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ATS verdict'),
        ),
    ]
