# Generated by Django 4.1.13 on 2026-07-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0021_jobapplication_ats_assessment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='company_address',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Company address'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='company_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='company_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
    ]
