# Generated by Django 4.1.13 on 2026-07-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0022_jobapplication_company_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='company_employees',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Employees'),
        ),
    ]
