# Generated by Django 4.1.13 on 2026-07-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0023_jobapplication_company_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_agency',
            field=models.BooleanField(blank=True, default=False, help_text='Company is hiring on behalf of an external client (staffing/recruitment agency)', null=True, verbose_name='Agency'),
        ),
    ]
