# Generated by Django 4.1.13 on 2026-07-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0024_jobapplication_is_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='application_sent',
            field=models.BooleanField(default=False, verbose_name='Отклик отправлен'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='not_interested',
            field=models.BooleanField(default=False, verbose_name='Неинтересна'),
        ),
    ]
