# Generated by Django 4.1.13 on 2026-07-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0025_jobapplication_application_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='company_website',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company website'),
        ),
    ]
