# Generated by Django 4.1.13 on 2026-07-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0026_jobapplication_company_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Закрыта'),
        ),
    ]
