# Generated by Django 4.1.13 on 2026-07-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0027_jobapplication_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='application_instructions',
            field=models.TextField(blank=True, help_text='Special instructions on how to apply: cover letter not wanted, specific channel, deadline, etc.', null=True, verbose_name='Application instructions (RU)'),
        ),
    ]
