# Generated by Django 4.1.13 on 2026-07-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0028_jobapplication_application_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_switzerland',
            field=models.BooleanField(default=False, help_text='Work location is in Switzerland (adds a work-permit note to cv_intro/cover_letter)', verbose_name='Switzerland'),
        ),
    ]
