# Generated by Django 4.1.13 on 2026-07-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0029_jobapplication_is_switzerland'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='required_experience',
            field=models.TextField(blank=True, null=True),
        ),
    ]
