# Generated by Django 4.1.13 on 2026-07-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0030_alter_jobapplication_required_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='ats_verdict',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='ATS verdict'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='company_address',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Company address'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='company_employees',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Employees'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='company_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='company_website',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Company website'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='contact_person',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='german_level',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job_title',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='location',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='minuses',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='other_benefits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='salary_range',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='vacation_days',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
