# Generated by Django 4.1.13 on 2026-07-05 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0031_alter_jobapplication_ats_verdict_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purpose', models.CharField(help_text="Which function/feature made this call, e.g. 'cover_letter'", max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('prompt_tokens', models.IntegerField(blank=True, null=True)),
                ('completion_tokens', models.IntegerField(blank=True, null=True)),
                ('total_tokens', models.IntegerField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=6, help_text='USD, as reported by OpenRouter', max_digits=10, null=True)),
                ('job_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_calls', to='job_application.jobapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
