# Generated by Django 4.1.13 on 2026-07-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0032_llmcalllog'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='german_blocks_daily_work',
            field=models.BooleanField(default=False, help_text='German is required for actual day-to-day work, not just a nice-to-have', verbose_name='German blocks daily work'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='has_growth_signal',
            field=models.BooleanField(default=False, help_text='Vacancy signals company growth/stability (funding round, growing team, named clients, YoY growth)', verbose_name='Growth signal'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='has_overregulated_flag',
            field=models.BooleanField(default=False, help_text='Vacancy signals a heavily regulated environment that limits day-to-day experimentation', verbose_name='Overregulated flag'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='has_toxic_flag',
            field=models.BooleanField(default=False, help_text='Vacancy signals a toxic/high-pressure culture ("top-1%", "extreme ownership", long hours)', verbose_name='Toxic culture flag'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='is_high_upside_brand',
            field=models.BooleanField(default=False, help_text='Manually flag an asymmetric-upside bet (brand/scale) that should sit in Tier C regardless of score', verbose_name='High-upside brand (manual override)'),
        ),
    ]
