# Generated by Django 4.1.13 on 2026-07-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0033_jobapplication_german_blocks_daily_work_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='agency_end_client_verified',
            field=models.BooleanField(default=False, help_text='Real employer behind this agency listing is known and good - lifts the default Tier B cap', verbose_name='Agency end-client verified good'),
        ),
    ]
