# Generated by Django 4.1.13 on 2026-07-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0034_jobapplication_agency_end_client_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='company_offices',
            field=models.JSONField(blank=True, default=list, help_text='All known offices found during research: [{address, lat, lng}, ...]. First entry mirrors company_address/company_lat/company_lng.', verbose_name='Company offices'),
        ),
    ]
