# Generated by Django 4.1.13 on 2026-07-05 23:06

from django.db import migrations, models


def populate_work_mode(apps, schema_editor):
    JobApplication = apps.get_model('job_application', 'JobApplication')
    JobApplication.objects.filter(is_remote=True).update(work_mode='remote')
    JobApplication.objects.filter(is_remote=False).update(work_mode='office')


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0035_jobapplication_company_offices'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='work_mode',
            field=models.CharField(
                blank=True, null=True, default='office', max_length=10, verbose_name='Work mode',
                choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('office', 'Office')],
            ),
        ),
        migrations.RunPython(populate_work_mode, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='jobapplication',
            name='is_remote',
        ),
    ]
