# Generated by Django 4.1.13 on 2026-07-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0036_remove_jobapplication_is_remote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmcalllog',
            name='error',
            field=models.TextField(blank=True, help_text='Exception message if the call failed', null=True),
        ),
        migrations.AddField(
            model_name='llmcalllog',
            name='latency_ms',
            field=models.IntegerField(blank=True, help_text='Wall-clock time for the API call, in milliseconds', null=True),
        ),
        migrations.AddField(
            model_name='llmcalllog',
            name='messages',
            field=models.JSONField(blank=True, help_text='Full list of messages sent to the LLM (system/user/etc.)', null=True),
        ),
        migrations.AddField(
            model_name='llmcalllog',
            name='response_text',
            field=models.TextField(blank=True, help_text='Raw text of the LLM response', null=True),
        ),
    ]
