# Generated by Django 4.1.13 on 2026-07-06 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0037_llmcalllog_error_llmcalllog_latency_ms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmcalllog',
            name='max_tokens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='llmcalllog',
            name='response_format',
            field=models.JSONField(blank=True, help_text='response_format kwarg sent to the LLM, if any', null=True),
        ),
        migrations.AddField(
            model_name='llmcalllog',
            name='retry_of',
            field=models.ForeignKey(blank=True, help_text='If this call is a manual retry of a failed call, the original log entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retries', to='job_application.llmcalllog'),
        ),
        migrations.AddField(
            model_name='llmcalllog',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
