# Generated by Django 4.1.13 on 2026-07-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0038_llmcalllog_max_tokens_llmcalllog_response_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
