# Generated by Django 4.1.7 on 2023-10-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_user_birth_date_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="website",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
