# Generated by Django 4.1.13 on 2024-02-26 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_about_me_de_user_about_me_en_user_about_me_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='about_me_de',
        ),
        migrations.RemoveField(
            model_name='user',
            name='about_me_en',
        ),
        migrations.RemoveField(
            model_name='user',
            name='about_me_ru',
        ),
        migrations.RemoveField(
            model_name='user',
            name='job_title_de',
        ),
        migrations.RemoveField(
            model_name='user',
            name='job_title_en',
        ),
        migrations.RemoveField(
            model_name='user',
            name='job_title_ru',
        ),
    ]
