# Generated by Django 4.1.13 on 2024-03-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_user_about_me_de_user_about_me_en_user_job_title_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover_letter_sample',
            field=models.TextField(blank=True, null=True),
        ),
    ]
