# Generated by Django 4.1.13 on 2026-06-25 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_user_cover_letter_sample'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='website',
            new_name='github',
        ),
    ]
