# Generated by Django 4.2.4 on 2024-02-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_education_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='description_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='faculty_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='faculty_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='faculty_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='school_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='school_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='school_ru',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
