# Generated by Django 4.2.4 on 2024-02-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='description_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_type_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_type_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_type_ru',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
