# Generated by Django 4.1.13 on 2024-02-26 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_skill_description_de_skill_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='description_de',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill_type_de',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill_type_en',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill_type_ru',
        ),
    ]
