# Generated by Django 4.1.13 on 2026-06-28 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_skill_description_de_skill_description_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='skill',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
