# Generated by Django 4.1.7 on 2023-08-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="github_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
