# Generated by Django 4.1.7 on 2023-08-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_alter_project_options_project_is_visible_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="screenshot_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
