# Generated by Django 4.1.7 on 2023-08-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_alter_project_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="screenshot_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
