# Generated by Django 4.1.13 on 2024-02-26 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_description_de_project_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description_de',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='project',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='project',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='name_ru',
        ),
    ]
